In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
data = pd.read_csv("Data/Data.csv")

In [3]:
# Loại bỏ các ký tự đặc biệt
def clean_text(text):
    text = re.sub(r'[^\w\s]', '', text)
    return text

data['comment_text_cleaned'] = data['comment_text'].apply(clean_text)

In [4]:
teencode = {
    "không": ["hong", "hok", "khom", "khum", "k", "ko", "khong", "hem", "no", "hơm", "hôn","hk", "hông"],
    "biết": ["bít", "biếc", "bt"],
    "rồi": ["ròi", "gòi", "rùi", "rui", "roi", "goy", "goi", "gui", "gùi", "ời", "oy", "òy", "roài", "ùi","r"],
    "tôi": ["teo", "toy", "tui", "t"],
    "em": ["iem", "e"],
    "yêu": ["iu", "ieo"],
    "ôi" : ["ưi", "ui"],
    "ừm" :["um", "ờm"],
    "ừ" : ["ò", "uk", "ầu", "ờ"],
    "chồng" : ["ck", "chòng"],
    "vợ": ["vk", "zợ", "zk"],
    "ông" : ["ong", "ô"],
    "anh": ["a"],
    "bé" :["pé"],
    "chị" : ["chụy", "cj", "cỵ", "cị"],
    "giờ" :["h"],
    "ch":["ck"],
    "ph":["f"],
    "th":["tk"],
    "nh":["nk"],
    "gì": ["j", "giề", "rì", "zì"],
    "muốn" : ["mún"],
    "học" : ["hc"],
    "bạn" :["bẹng", "bạng", "bn", "pạn"],
    "mày" :["m", "mèy", "mài"],
    "đang" : ["aq", "đaq", "đag", "dang", "dag"],
    "đường": ["đg"],
    "làm":['nàm', "lèm"],
    "cao":['kao'],
    'ch':['tr'],
    'tr':['ch'],
    'vậy':['zạy', 'zay', 'vại', 'dọ', 'dạ', 'zị', 'zậy', 'zọ', "v", 'z', 'dị'],
    "nội":['nụi'],
    "quen" :['wen'],
    "hoài" : ["quài"],
    "ỉa":['ẻ'],
    "hả":['hỏ', 'hẻ', 'hở'],
    "bà" :['pà'],
    "khùng" :["khùm", "khùn"],
    "điên" :["đin", "điêng"],
    "ngu" :["nguk"],
    "ngốc" :["ngok"],
    "được" :["dc", "dk", "duoc", "đc"],
    "trời" : ["chòi", "chời", "trùi", "tr"],
    "cũng" : ["cũm", "cx"],
    "nha": ["nhoa", "nho", "nhe"],
    "diễn viên" : ["dv"],
    "ca sĩ" : ["ca sỉ", "cs"],
    "mọi người" : ["mọi ngừi", "mn"],
    "thằng" : ["tk","thg"],
    "người": ["ngừi", "ng"],
    "quá": ["qá", "wa", "quớ"]
}

# Tạo từ điển đảo ngược cho việc thay thế
reverse_teencode = {teencode_word: full_word for full_word, teencode_list in teencode.items() for teencode_word in teencode_list}

# Hàm thay thế teencode bằng từ đầy đủ
def replace_teencode(text):
    words = text.split()
    replaced_words = [reverse_teencode.get(word, word) for word in words]
    return ' '.join(replaced_words)

# Áp dụng hàm replace_teencode vào cột comment_text_cleaned
data['comment_text_cleaned'] = data['comment_text_cleaned'].apply(replace_teencode)


In [5]:
# Chuyển đổi về chữ thường để giảm đa dạng
data['comment_text_cleaned'] = data['comment_text_cleaned'].str.lower()

In [6]:
# Loại bỏ các từ dừng (stop words)

# Đọc các từ trong file stop words
with open('Vietnamese_data/vietnamese-stop-words.txt', 'r', encoding='utf-8') as file:
    stop_words = set(file.read())

# Hàm loại bỏ các từ dừng
def remove_stopwords(text):
    return ' '.join([word for word in text.split() if word not in stop_words])

# Áp dụng hàm remove_stopwords vào cột comment_text_cleaned
data['comment_text_cleaned'] = data['comment_text_cleaned'].apply(remove_stopwords)

In [25]:
# Loại bỏ các từ dừng (stop words)

# Đọc các từ trong file stop words
with open('Vietnamese_data/vnpernames.txt', 'r', encoding='utf-8') as file:
    stop_words = set(file.read().split())

# Hàm loại bỏ các từ dừng
def remove_stopwords(text):
    return ' '.join([word for word in text.split() if word not in stop_words])

# Áp dụng hàm remove_stopwords vào cột comment_text_cleaned
data['comment_text_cleaned'] = data['comment_text_cleaned'].apply(remove_stopwords)

In [26]:
data

comment_text  label  \
0     Thật ra cái cfs nói ko sai mà. Lứa dv 8x còn c...      0   
1     JCW có bộ Tội Ác Kinh Hoàng hay qá trời mỗi tộ...      1   
2     Lee Min Ho đẹp trai mà một màu quá, đóng vai g...      0   
3     Xem SJK đóng cậu út nhà tài phiệt thấy tụt moo...     -1   
4     Trong này t công nhận diễn xuất của 3 ông\nKSH...      1   
...                                                 ...    ...   
2704  Dm ad viết t đọc t còn nhục hộ đám fan luôn ấy :)     -1   
2705  Viết cái lyric thôi cũng éo ra hồn nữa là prod...     -1   
2706  Tại con người ai cũng biết ngại, rất tiếc ảnh ...     -1   
2707  Dẹp cái ông jack vớ vẩn này luôn đi cho trong ...     -1   
2708  Mình thấy nước ngoài người ta làm nhạc là từ p...      0   

                                   comment_text_cleaned  
0     thật ra cái cfs nói không sai mà lứa diễn viên...  
1     jcw có bộ tội ác kinh hoàng hay quá trời mỗi t...  
2     lee min ho đẹp trai mà một màu quá đóng vai gì...  
3     xem sjk đóng cậu út nhà tài phiệt thấy tụt moo...  
4     trong này tôi nhận diễn xuất của 3 ông ksh ljs...  
...                                                 ...  
2704  dm ad viết tôi đọc tôi còn nhục hộ đám fan luô...  
2705  viết cái lyric thôi cũng éo ra hồn nữa là prod...  
2706  tại con người ai cũng biết ngại rất tiếc ảnh k...  
2707  dẹp cái ông jack vớ vẩn này luôn đi cho trong ...  
2708  mình thấy nước ngoài người ta làm nhạc là pian...  

[2709 rows x 3 columns]

In [27]:
from sklearn.model_selection import train_test_split

# X là features, y là labels
X_train, X_temp, y_train, y_temp  = train_test_split(data['comment_text_cleaned'],data['label'], test_size=0.4, random_state=42)

# Chia tập temp thành tập test và validation
X_test, X_val, y_test, y_val = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

In [28]:
vectorizer = CountVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)
X_val_vec = vectorizer.transform(X_val)

In [29]:
model = LogisticRegression()
model.fit(X_train_vec, y_train)
y_test_pred = model.predict(X_test_vec)
test_accuracy = accuracy_score(y_test, y_test_pred)
test_class_report = classification_report(y_test, y_test_pred)

# In độ chính xác và ma trận nhầm lẫn trên tập test
print(f"Độ chính xác trên tập test: {test_accuracy:.2f}")
print(test_class_report)

# Bước 5: Đánh giá mô hình trên tập validation
y_val_pred = model.predict(X_val_vec)
val_accuracy = accuracy_score(y_val, y_val_pred)
val_class_report = classification_report(y_val, y_val_pred)

# In độ chính xác và ma trận nhầm lẫn trên tập validation
print(f"Độ chính xác trên tập validation: {val_accuracy:.2f}")
print("Báo cáo phân loại trên tập validation:")
print(val_class_report)

Độ chính xác trên tập test: 0.72
              precision    recall  f1-score   support

          -1       0.69      0.51      0.59       144
           0       0.73      0.84      0.78       296
           1       0.69      0.65      0.67       102

    accuracy                           0.72       542
   macro avg       0.71      0.67      0.68       542
weighted avg       0.71      0.72      0.71       542

Độ chính xác trên tập validation: 0.71
Báo cáo phân loại trên tập validation:
              precision    recall  f1-score   support

          -1       0.63      0.48      0.54       134
           0       0.72      0.84      0.78       299
           1       0.80      0.65      0.72       109

    accuracy                           0.71       542
   macro avg       0.71      0.66      0.68       542
weighted avg       0.71      0.71      0.71       542



In [30]:
model = DecisionTreeClassifier(random_state=42)
model.fit(X_train_vec, y_train)
y_test_pred = model.predict(X_test_vec)
test_accuracy = accuracy_score(y_test, y_test_pred)
test_class_report = classification_report(y_test, y_test_pred)

# In độ chính xác và ma trận nhầm lẫn trên tập test
print(f"Độ chính xác trên tập test: {test_accuracy:.2f}")
print(test_class_report)

# Bước 5: Đánh giá mô hình trên tập validation
y_val_pred = model.predict(X_val_vec)
val_accuracy = accuracy_score(y_val, y_val_pred)
val_class_report = classification_report(y_val, y_val_pred)

# In độ chính xác và ma trận nhầm lẫn trên tập validation
print(f"Độ chính xác trên tập validation: {val_accuracy:.2f}")
print("Báo cáo phân loại trên tập validation:")
print(val_class_report)

Độ chính xác trên tập test: 0.60
              precision    recall  f1-score   support

          -1       0.52      0.47      0.49       144
           0       0.67      0.68      0.67       296
           1       0.51      0.57      0.54       102

    accuracy                           0.60       542
   macro avg       0.57      0.57      0.57       542
weighted avg       0.60      0.60      0.60       542

Độ chính xác trên tập validation: 0.61
Báo cáo phân loại trên tập validation:
              precision    recall  f1-score   support

          -1       0.46      0.43      0.44       134
           0       0.67      0.70      0.68       299
           1       0.63      0.59      0.61       109

    accuracy                           0.61       542
   macro avg       0.58      0.57      0.58       542
weighted avg       0.61      0.61      0.61       542



In [7]:
from sklearn.model_selection import train_test_split

# X là features, y là labels
X_train, X_temp, y_train, y_temp  = train_test_split(data['comment_text_cleaned'],data['label'], test_size=0.4, random_state=42)

# Chia tập temp thành tập test và validation
X_test, X_val, y_test, y_val = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

In [8]:
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,confusion_matrix, classification_report

In [9]:
vectorizer = CountVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)
X_val_vec = vectorizer.transform(X_val)

In [10]:
model = DecisionTreeClassifier(random_state=42)
model.fit(X_train_vec, y_train)


DecisionTreeClassifier(random_state=42)

In [11]:
y_test_pred = model.predict(X_test_vec)
test_accuracy = accuracy_score(y_test, y_test_pred)
test_class_report = classification_report(y_test, y_test_pred)

# In độ chính xác và ma trận nhầm lẫn trên tập test
print(f"Độ chính xác trên tập test: {test_accuracy:.2f}")
print(test_class_report)

# Bước 5: Đánh giá mô hình trên tập validation
y_val_pred = model.predict(X_val_vec)
val_accuracy = accuracy_score(y_val, y_val_pred)
val_class_report = classification_report(y_val, y_val_pred)

# In độ chính xác và ma trận nhầm lẫn trên tập validation
print(f"Độ chính xác trên tập validation: {val_accuracy:.2f}")
print("Báo cáo phân loại trên tập validation:")
print(val_class_report)

Độ chính xác trên tập test: 0.60
              precision    recall  f1-score   support

          -1       0.52      0.45      0.48       144
           0       0.66      0.68      0.67       296
           1       0.50      0.55      0.52       102

    accuracy                           0.60       542
   macro avg       0.56      0.56      0.56       542
weighted avg       0.59      0.60      0.59       542

Độ chính xác trên tập validation: 0.60
Báo cáo phân loại trên tập validation:
              precision    recall  f1-score   support

          -1       0.46      0.43      0.44       134
           0       0.65      0.70      0.68       299
           1       0.62      0.52      0.57       109

    accuracy                           0.60       542
   macro avg       0.58      0.55      0.56       542
weighted avg       0.60      0.60      0.60       542



In [12]:
param_grid = {
    'criterion': ['gini', 'entropy'],  # Tiêu chuẩn để đo độ tinh khiết của nút
    'max_depth': [None, 10, 20, 30, 40, 50],  # Độ sâu tối đa của cây
    'min_samples_split': [2, 5, 10],  # Số lượng mẫu tối thiểu cần thiết để chia một nút
    'min_samples_leaf': [1, 2, 4]  # Số lượng mẫu tối thiểu cần thiết để ở lại một nút lá
}

# Sử dụng GridSearchCV để tìm kiếm tham số tốt nhất
grid_search = GridSearchCV(model, param_grid, cv=5, scoring='accuracy', n_jobs=-1)
grid_search.fit(X_train_vec, y_train)

# In tham số tốt nhất
print("Tham số tốt nhất:", grid_search.best_params_)

# Sử dụng mô hình tốt nhất để dự đoán và đánh giá trên tập test
best_model = grid_search.best_estimator_
y_test_pred = best_model.predict(X_test_vec)
test_accuracy = accuracy_score(y_test, y_test_pred)
test_class_report = classification_report(y_test, y_test_pred)

# In độ chính xác và ma trận nhầm lẫn trên tập test
print(f"Độ chính xác trên tập test: {test_accuracy:.2f}")
print("Báo cáo phân loại trên tập test:")
print(test_class_report)

# Đánh giá mô hình trên tập validation
y_val_pred = best_model.predict(X_val_vec)
val_accuracy = accuracy_score(y_val, y_val_pred)
val_class_report = classification_report(y_val, y_val_pred)

# In độ chính xác và ma trận nhầm lẫn trên tập validation
print(f"Độ chính xác trên tập validation: {val_accuracy:.2f}")
print("Báo cáo phân loại trên tập validation:")
print(val_class_report)

Tham số tốt nhất: {'criterion': 'gini', 'max_depth': 10, 'min_samples_leaf': 4, 'min_samples_split': 10}
Độ chính xác trên tập test: 0.61
Báo cáo phân loại trên tập test:
              precision    recall  f1-score   support

          -1       0.69      0.20      0.31       144
           0       0.60      0.89      0.72       296
           1       0.55      0.35      0.43       102

    accuracy                           0.61       542
   macro avg       0.62      0.48      0.49       542
weighted avg       0.62      0.61      0.56       542

Độ chính xác trên tập validation: 0.59
Báo cáo phân loại trên tập validation:
              precision    recall  f1-score   support

          -1       0.51      0.19      0.27       134
           0       0.60      0.87      0.71       299
           1       0.62      0.33      0.43       109

    accuracy                           0.59       542
   macro avg       0.58      0.46      0.47       542
weighted avg       0.58      0.59      0.55 

In [31]:

# Tạo vector đặc trưng từ sentiment words
sentiment_words = ["hay","hát hay","diễn hay","thích","mê","ghét","trà xanh","drama","thằng chó","tệ"]
vectorizer = CountVectorizer(vocabulary=sentiment_words)


# Tạo pipeline với CountVectorizer và Logistic Regression
pipeline = Pipeline([
    ('vect', vectorizer),
    ('clf', LogisticRegression())
])

# Huấn luyện mô hình
pipeline.fit(X_train, y_train)

# Dự đoán và đánh giá mô hình
y_pred = pipeline.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.5608856088560885


In [13]:
from sklearn.linear_model import LogisticRegression

In [14]:
model = LogisticRegression()
model.fit(X_train_vec, y_train)
y_test_pred = model.predict(X_test_vec)
test_accuracy = accuracy_score(y_test, y_test_pred)
test_class_report = classification_report(y_test, y_test_pred)

# In độ chính xác và ma trận nhầm lẫn trên tập test
print(f"Độ chính xác trên tập test: {test_accuracy:.2f}")
print(test_class_report)

# Bước 5: Đánh giá mô hình trên tập validation
y_val_pred = model.predict(X_val_vec)
val_accuracy = accuracy_score(y_val, y_val_pred)
val_class_report = classification_report(y_val, y_val_pred)

# In độ chính xác và ma trận nhầm lẫn trên tập validation
print(f"Độ chính xác trên tập validation: {val_accuracy:.2f}")
print("Báo cáo phân loại trên tập validation:")
print(val_class_report)

Độ chính xác trên tập test: 0.71
              precision    recall  f1-score   support

          -1       0.68      0.51      0.58       144
           0       0.73      0.84      0.78       296
           1       0.71      0.64      0.67       102

    accuracy                           0.71       542
   macro avg       0.71      0.66      0.68       542
weighted avg       0.71      0.71      0.71       542

Độ chính xác trên tập validation: 0.72
Báo cáo phân loại trên tập validation:
              precision    recall  f1-score   support

          -1       0.65      0.48      0.55       134
           0       0.72      0.85      0.78       299
           1       0.80      0.64      0.71       109

    accuracy                           0.72       542
   macro avg       0.72      0.66      0.68       542
weighted avg       0.72      0.72      0.71       542



In [15]:
param_grid = {
    'C': [0.01, 0.1, 1, 10, 100],  # Hệ số điều chỉnh cho regularization
    'solver': ['liblinear', 'saga'],  # Thuật toán để tối ưu hóa
    'max_iter': [200, 300,400]  # Số lần lặp tối đa
}

# Sử dụng GridSearchCV để tìm kiếm tham số tốt nhất
grid_search = GridSearchCV(model, param_grid, cv=5, scoring='accuracy', n_jobs=-1)
grid_search.fit(X_train_vec, y_train)

# In tham số tốt nhất
print("Tham số tốt nhất:", grid_search.best_params_)

# Sử dụng mô hình tốt nhất để dự đoán và đánh giá trên tập test
best_model = grid_search.best_estimator_
y_test_pred = best_model.predict(X_test_vec)
test_accuracy = accuracy_score(y_test, y_test_pred)
test_class_report = classification_report(y_test, y_test_pred)

# In độ chính xác và ma trận nhầm lẫn trên tập test
print(f"Độ chính xác trên tập test: {test_accuracy:.2f}")
print("Báo cáo phân loại trên tập test:")
print(test_class_report)

# Đánh giá mô hình trên tập validation
y_val_pred = best_model.predict(X_val_vec)
val_accuracy = accuracy_score(y_val, y_val_pred)
val_class_report = classification_report(y_val, y_val_pred)

# In độ chính xác và ma trận nhầm lẫn trên tập validation
print(f"Độ chính xác trên tập validation: {val_accuracy:.2f}")
print("Báo cáo phân loại trên tập validation:")
print(val_class_report)

Tham số tốt nhất: {'C': 0.1, 'max_iter': 300, 'solver': 'saga'}
Độ chính xác trên tập test: 0.70
Báo cáo phân loại trên tập test:
              precision    recall  f1-score   support

          -1       0.69      0.44      0.54       144
           0       0.70      0.87      0.78       296
           1       0.73      0.60      0.66       102

    accuracy                           0.70       542
   macro avg       0.71      0.64      0.66       542
weighted avg       0.71      0.70      0.69       542

Độ chính xác trên tập validation: 0.71
Báo cáo phân loại trên tập validation:
              precision    recall  f1-score   support

          -1       0.62      0.42      0.50       134
           0       0.71      0.85      0.78       299
           1       0.80      0.68      0.73       109

    accuracy                           0.71       542
   macro avg       0.71      0.65      0.67       542
weighted avg       0.71      0.71      0.70       542



d:\Setup\miniconda\envs\Nyh_Py\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


In [16]:
from sklearn.ensemble import RandomForestClassifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier.fit(X_train_vec, y_train)

# Dự đoán nhãn cho tập test
y_pred = rf_classifier.predict(X_test_vec)

# Đánh giá hiệu suất của mô hình
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.2f}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(class_report)

Accuracy: 0.67
Confusion Matrix:
[[ 45  95   4]
 [  9 270  17]
 [  2  50  50]]
Classification Report:
              precision    recall  f1-score   support

          -1       0.80      0.31      0.45       144
           0       0.65      0.91      0.76       296
           1       0.70      0.49      0.58       102

    accuracy                           0.67       542
   macro avg       0.72      0.57      0.60       542
weighted avg       0.70      0.67      0.64       542



In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(max_features=5000)
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

# Khởi tạo và huấn luyện mô hình Random Forest
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier.fit(X_train_tfidf, y_train)

# Dự đoán nhãn cho tập test
y_pred = rf_classifier.predict(X_test_tfidf)

# Đánh giá hiệu suất của mô hình
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.2f}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(class_report)

Accuracy: 0.67
Confusion Matrix:
[[ 42 100   2]
 [ 11 275  10]
 [  1  53  48]]
Classification Report:
              precision    recall  f1-score   support

          -1       0.78      0.29      0.42       144
           0       0.64      0.93      0.76       296
           1       0.80      0.47      0.59       102

    accuracy                           0.67       542
   macro avg       0.74      0.56      0.59       542
weighted avg       0.71      0.67      0.64       542



In [18]:
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}
rf_classifier = RandomForestClassifier(random_state=42)

# Sử dụng GridSearchCV để tìm kiếm tham số tốt nhất
grid_search = GridSearchCV(rf_classifier, param_grid, cv=5, scoring='accuracy', n_jobs=-1)
grid_search.fit(X_train_tfidf, y_train)

# In ra tham số tốt nhất
print("Tham số tốt nhất:", grid_search.best_params_)

# Sử dụng mô hình tốt nhất để dự đoán và đánh giá trên tập test
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test_tfidf)

# Đánh giá hiệu suất của mô hình
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.2f}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(class_report)

Tham số tốt nhất: {'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 10, 'n_estimators': 200}
Accuracy: 0.68
Confusion Matrix:
[[ 41 101   2]
 [  8 280   8]
 [  1  53  48]]
Classification Report:
              precision    recall  f1-score   support

          -1       0.82      0.28      0.42       144
           0       0.65      0.95      0.77       296
           1       0.83      0.47      0.60       102

    accuracy                           0.68       542
   macro avg       0.76      0.57      0.60       542
weighted avg       0.73      0.68      0.64       542



In [20]:
from sklearn.pipeline import Pipeline
pipeline = Pipeline([
    ('vect', CountVectorizer(ngram_range=(1, 2))),
    ('clf', LogisticRegression())
])

# Huấn luyện mô hình
pipeline.fit(X_train, y_train)

# Dự đoán và đánh giá mô hình
y_pred = pipeline.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.2f}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(class_report)

Accuracy: 0.72
Confusion Matrix:
[[ 69  72   3]
 [ 18 262  16]
 [  5  39  58]]
Classification Report:
              precision    recall  f1-score   support

          -1       0.75      0.48      0.58       144
           0       0.70      0.89      0.78       296
           1       0.75      0.57      0.65       102

    accuracy                           0.72       542
   macro avg       0.74      0.64      0.67       542
weighted avg       0.72      0.72      0.71       542



In [22]:
from sklearn.pipeline import Pipeline
pipeline = Pipeline([
    ('vect', CountVectorizer(ngram_range=(2, 3))),
    ('clf', LogisticRegression())
])

# Huấn luyện mô hình
pipeline.fit(X_train, y_train)

# Dự đoán và đánh giá mô hình
y_pred = pipeline.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.2f}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(class_report)

Accuracy: 0.63
Confusion Matrix:
[[ 22 122   0]
 [  4 283   9]
 [  0  64  38]]
Classification Report:
              precision    recall  f1-score   support

          -1       0.85      0.15      0.26       144
           0       0.60      0.96      0.74       296
           1       0.81      0.37      0.51       102

    accuracy                           0.63       542
   macro avg       0.75      0.49      0.50       542
weighted avg       0.71      0.63      0.57       542



In [46]:
from sklearn.ensemble import BaggingClassifier,VotingClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB

In [42]:
base_model = LogisticRegression()

# Tạo BaggingClassifier với mô hình cơ sở là Logistic Regression
bagging_model = BaggingClassifier(base_model, n_estimators=10, random_state=42)

# Huấn luyện mô hình
bagging_model.fit(X_train_vec, y_train)


# Dự đoán và đánh giá mô hình
y_pred = bagging_model.predict(X_test_vec)
accuracy = accuracy_score(y_test, y_pred)
class_report = classification_report(y_test, y_pred)
print("Accuracy:", accuracy)
print(class_report)

Accuracy: 0.7140221402214022
              precision    recall  f1-score   support

          -1       0.75      0.46      0.57       144
           0       0.71      0.87      0.78       296
           1       0.69      0.62      0.65       102

    accuracy                           0.71       542
   macro avg       0.72      0.65      0.67       542
weighted avg       0.72      0.71      0.70       542



In [52]:
base_models = [
    ('lr', LogisticRegression()),
    ('svm', SVC(kernel='linear', probability=True)),
    ('nb', MultinomialNB())
]
ensemble = VotingClassifier(base_models)
# Tạo BaggingClassifier với các mô hình cơ sở
bagging_model = BaggingClassifier(ensemble, n_estimators=20, random_state=42)

# Huấn luyện mô hình
bagging_model.fit(X_train_vec, y_train)


# Dự đoán và đánh giá mô hình
y_pred = bagging_model.predict(X_test_vec)
accuracy = accuracy_score(y_test, y_pred)
class_report = classification_report(y_test, y_pred)
print("Accuracy:", accuracy)
print(class_report)

Accuracy: 0.7214022140221402
              precision    recall  f1-score   support

          -1       0.72      0.50      0.59       144
           0       0.72      0.87      0.79       296
           1       0.74      0.61      0.67       102

    accuracy                           0.72       542
   macro avg       0.73      0.66      0.68       542
weighted avg       0.72      0.72      0.71       542



In [53]:
base_models = [
    ('lr', LogisticRegression()),
    ('svm', SVC(kernel='linear', probability=True)),
    ('nb', MultinomialNB())
]
ensemble = VotingClassifier(base_models)
# Tạo BaggingClassifier với các mô hình cơ sở
bagging_model = BaggingClassifier(ensemble, n_estimators=30
                                  , random_state=42)

# Huấn luyện mô hình
bagging_model.fit(X_train_vec, y_train)


# Dự đoán và đánh giá mô hình
y_pred = bagging_model.predict(X_test_vec)
accuracy = accuracy_score(y_test, y_pred)
class_report = classification_report(y_test, y_pred)
print("Accuracy:", accuracy)
print(class_report)

Accuracy: 0.7214022140221402
              precision    recall  f1-score   support

          -1       0.70      0.50      0.58       144
           0       0.72      0.86      0.79       296
           1       0.74      0.62      0.67       102

    accuracy                           0.72       542
   macro avg       0.72      0.66      0.68       542
weighted avg       0.72      0.72      0.71       542



In [54]:
base_models = [
    ('lr', LogisticRegression()),
    ('svm', SVC(kernel='linear', probability=True)),
    ('nb', MultinomialNB())
]
ensemble = VotingClassifier(base_models)
# Tạo BaggingClassifier với các mô hình cơ sở
bagging_model = BaggingClassifier(ensemble, n_estimators=25
                                  , random_state=42)

# Huấn luyện mô hình
bagging_model.fit(X_train_vec, y_train)


# Dự đoán và đánh giá mô hình
y_pred = bagging_model.predict(X_test_vec)
accuracy = accuracy_score(y_test, y_pred)
class_report = classification_report(y_test, y_pred)
print("Accuracy:", accuracy)
print(class_report)


Accuracy: 0.7195571955719557
              precision    recall  f1-score   support

          -1       0.72      0.50      0.59       144
           0       0.72      0.86      0.78       296
           1       0.73      0.61      0.66       102

    accuracy                           0.72       542
   macro avg       0.72      0.66      0.68       542
weighted avg       0.72      0.72      0.71       542

